version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - kenkeiras
  assignees:
  - kenkeiras
  ignore:
  - dependency-name: poison
    versions:
    - ">= 4.a, < 5"
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: postgrex
    versions:
    - 0.15.8
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - kenkeiras
  assignees:
  - kenkeiras
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - kenkeiras
  assignees:
  - kenkeiras
